

services:
  # Base de données MySQL pour PrestaShop
  db:
    image: mariadb:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_net

  # Serveur PrestaShop - Environnement de recette
  prestashop_recette:
    image: prestashop/prestashop:${PRESTASHOP_VERSION}
    container_name: ${PRESTASHOP_RECETTE_CONTAINER_NAME}
    environment:
      DB_SERVER: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      PS_DEV_MODE: 1  # Mode développement
    ports:
      - "${PRESTASHOP_RECETTE_PORT}:80"
    volumes:
      - ./prestashop_recette_data:/var/www/html
    depends_on:
      - db
    networks:
      - prestashop_net

# Réseau et volumes partagés
volumes:
  db_data:
  prestashop_recette_data:

networks:
  prestashop_net:
    driver: bridge

