services:
  # Base de données MySQL pour PrestaShop
  db:
    image: mariadb:latest
    container_name: mysql_prestashop
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prestashop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: Test1234!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_net

  # Serveur PrestaShop - Environnement de recette
  prestashop_recette:
    image: prestashop/prestashop:latest
    container_name: prestashop_recette
    environment:
      DB_SERVER: db
      DB_NAME: prestashop_db
      DB_USER: user
      DB_PASSWORD: Test1234!
      PS_DEV_MODE: 1  # Mode développement
    ports:
      - "8088:80"
    volumes:
      - ./prestashop_recette_data:/var/www/html
    depends_on:
      - db
    networks:
      - prestashop_net

# Réseau et volumes partagés
volumes:
  db_data:
  prestashop_recette_data:

networks:
  prestashop_net:
    driver: bridge
