<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFyFbtwE\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFyFbtwE/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFyFbtwE.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFyFbtwE\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerFyFbtwE\appAppKernelDevDebugContainer([
    'container.build_hash' => 'FyFbtwE',
    'container.build_id' => '8f6dbbab',
    'container.build_time' => 1728048326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFyFbtwE');
