<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXMYEdBP\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXMYEdBP/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXMYEdBP.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXMYEdBP\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerXMYEdBP\appAppKernelDevDebugContainer([
    'container.build_hash' => 'XMYEdBP',
    'container.build_id' => 'c46c6f4d',
    'container.build_time' => 1727969914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXMYEdBP');
