<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPUsxiTi\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPUsxiTi/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPUsxiTi.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPUsxiTi\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPUsxiTi\appAppKernelProdContainer([
    'container.build_hash' => 'PUsxiTi',
    'container.build_id' => '04b13114',
    'container.build_time' => 1727969896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPUsxiTi');
