<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDvWv3v7\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDvWv3v7/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDvWv3v7.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDvWv3v7\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDvWv3v7\appAppKernelProdContainer([
    'container.build_hash' => 'DvWv3v7',
    'container.build_id' => 'fc3b4358',
    'container.build_time' => 1728029008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDvWv3v7');
