<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6cVS5I9\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6cVS5I9/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container6cVS5I9.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container6cVS5I9\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container6cVS5I9\appAppKernelProdContainer([
    'container.build_hash' => '6cVS5I9',
    'container.build_id' => 'd2d956b3',
    'container.build_time' => 1728048314,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6cVS5I9');
