<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwBQ1TPFaD9mcGb8/yxQd'."\n".'scsNLUXADLnJI4QKwhaKRvOt8iCI78c8vgqTExLq/0vlipek0tO7VZPFuG/C9zS8'."\n".'lqmDNVTJUIhgPCS4wlyQxwRIEl0sEk8mbjLqeKvOqQ5CWviZjMGqY7wcDT56hVUp'."\n".'jIfwTtjBBf4frJh760hejULh4w8/Ie8KZjjikJqs+4IOgKWwHvasqDYQ1TR41REO'."\n".'glcD4H7AQgQgjBqgtOSHjtSxLDU4E0+extkWkiYAJCQcPv5pwmOmi4rnI4GfaDOC'."\n".'Y25FqKgmkSqD5GbbmQ6Ju0B4Y5exccK7VTRFrwfb8Fq+HTycwI5jL/8IYZ44IjjS'."\n".'QQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
