<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0T8VrDZ92Min0t0L98Ey'."\n".'S3FDDpSjaQXIOsKGUtf0mhNXL7Y7fd8FSc7h+a1afV8Fbo0wglQFxjRcQFmoXzVq'."\n".'R7UI5LNcQduinojy8HR56Fs5N3vpaT1Rs1AS/2kv40QeMHftTjleFT2pbSrxG1ox'."\n".'Y6MLkzqWpD8hUaCwc+QhCqiE+w1CkLad+8grz38Fyqko7W0JzQIXTHGb0oohbxdD'."\n".'o0FNK84g/hFK5ACfwI8z1R53bHVep/gTFBKRpRKWQ/JXB2bM8enk85JyZDG8jvxB'."\n".'0KcPe1MS8QbeKYdQyg1NPCCBy/h4Bxvwy9SP1dYfL9fTkVCJxp+ZRO9oIRM8BSD0'."\n".'rQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
